site_name: hrz's notes

theme:
  name: material

markdown_extensions:
   - pymdownx.arithmatex

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
